name: Deploy to GitHub Pages

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  shared-install:
    uses: ./.github/common-actions/install
  build:
    needs: shared-install
    runs-on: ubuntu-latest

    steps:
      - run: pnpm --filter web  build
      - uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./web/dist

      #- name: Tests
      #  run: pnpm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./web/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
