name: Publish to npm

on:
  push:
    tags:
      - 'v*'  # Aciona o workflow quando uma tag de versão é criada, ex: v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm --filter grid-table build

      - name: Publish to npm
        run: pnpm publish --filter grid-table --access public
        env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
